name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - name: Run AI Code Review
        uses: Kazuya4395/vertex-api-pr-review@v1 # Replace with your repo
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gcp-project-id: ${{ secrets.GCP_PROJECT_ID }}
          gcp-location: ${{ secrets.GCP_LOCATION }}
          gcp-credentials: ${{ secrets.GCP_CREDENTIALS }}
          # Optional inputs
          # model: 'gemini-1.5-pro'
          # prompt-path: '.github/prompts/custom-prompt.md'
          # diff-size-limit: '200000'
          # timeout: '180000'
